name: Update Helm Tarball
on:
  workflow_call:

jobs:
  update-helm-deps-tarballs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Prepare Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      
      - name: Prepare yq
        uses: mikefarah/yq@master
      
      - name: update all charts
        run: |
          set -eu
          
          for chartfile in $(find . -name Chart.yaml -type f); do
            chartdir=$(dirname "$chartfile")

            deplength=$(yq '.dependencies | length' "$chartfile")

            if [ "$deplength" -gt "0" ]; then
               pushd "$chartdir"
               helm dependency update
               popd
            else
               echo "Skipping $chartfile since no dependencies were found."
               continue
            fi
            
            git add "${chartdir}"
          done
      
      - name: Check if an update happened
        id: diff-check
        continue-on-error: true
        run: |
          git diff --cached --exit-code ':(exclude)Chart.lock'

      - name: setup git config
        if: steps.diff-check.outcome == 'failure'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: commit
        if: steps.diff-check.outcome == 'failure'
        run: |
          set -eux

          # Stage the file, commit and push
          git add .
          git checkout -b "${GITHUB_HEAD_REF}"
          git commit -m "Update Helm Tarballs"
          git push origin "${GITHUB_HEAD_REF}"
